:alembic: try to release cont.

diff --git a/Makefile.toml b/Makefile.toml
--- a/Makefile.toml
+++ b/Makefile.toml
@@ -190,11 +190,11 @@ Expand-Archive -LiteralPath $output -Destination .
 condition = { env_set = [ "GITHUB_RELEASE_PATH", "GITHUB_REPOSITORY", "GITHUB_TOKEN", "DIST_NAME", "DIST_PATH", "DIST_EXT"] }
 script_runner = "@shell"
 script= [
-# ./github-release release --tag "${DIST_VERSION}" || echo "skip"
 '''
 cd ${GITHUB_RELEASE_PATH}
 export GITHUB_USER=$(dirname $GITHUB_REPOSITORY)
 export GITHUB_REPO=$(basename $GITHUB_REPOSITORY)
+./github-release release --tag "${DIST_VERSION}" || echo "ignore error"
 ./github-release upload --tag "${DIST_VERSION}" --name "${DIST_NAME}.${DIST_EXT}" --file "${GITHUB_RELEASE_PATH_REV}${DIST_PATH}.${DIST_EXT}"
 ''',
 ]
@@ -206,10 +206,10 @@ script_runner = "powershell"
 script_extension = "ps1"
 script= [
 # multi-line command with \ at EOL doesn't work on windows
-# github-release.exe release --tag "${DIST_VERSION}"
 '''
 cd ${GITHUB_RELEASE_PATH}
 $GITHUB_USER,$GITHUB_REPO=$GITHUB_REPOSITORY.split("/")
+github-release.exe release --tag "${DIST_VERSION}" -ErrorAction SilentlyContinue
 github-release.exe upload --tag "${DIST_VERSION}" --name "${DIST_NAME}.${DIST_EXT}" --file "${GITHUB_RELEASE_PATH_REV}${DIST_PATH}.${DIST_EXT}"
 ''',
 ]
